Repository beyond-sw-camp/be08-fin-HQ-Heroes, pull requests merged in 2024-11, with the labels that each got.

#745 [fix/#744] 교육 백엔드 코드 수정 및 에러 고침
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
Labels: 🐞 BugFix

#747 [design/#746] attendanceBox 수정
  Frontend/src/layout/AttendanceBox.vue
Labels: 🖌️Design

#749 [refactor/#748/page] 공지사항 카테고리 수정 및 퇴직시 근무년수 기본값 설정
  Frontend/src/views/pages/admin/NoticeWritePage.vue
  Frontend/src/views/pages/retirement/retirement-funds.vue
Labels: 🔨 Refactor

#751 [fix#750] 11/1 코드리뷰 버그 수정 : 비밀번호 변경 오류 수정, 평가일 기준으로 평가 결과 정렬
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🐞 BugFix

#753 [design/#752] 교육 및 자격증 페이지 수정
  Frontend/src/views/pages/admin/EducationWritePage.vue
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
Labels: 🖌️Design

#755 [feat#754] 휴가 취소 신청, 승인, 반려 알림 자동 발송 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
Labels: ✨ Feature

#757 [design#756] 로그인, 비밀번호 재발급 페이지 디자인 수정
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/ResetPWPage.vue
Labels: 🖌️Design

#759 [fix#758] 자격증 쪽 알림 자동 발송 DTO 문제 해결
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
Labels: 🐞 BugFix

#761 [feat/#760] 출퇴근 버튼 클릭시 한번 더 물어보는 기능 추가
  Frontend/src/layout/AttendanceBox.vue
Labels: ✨ Feature

#763 [feat/#762] 취소 반려됨 추가해서 일수 차감 안되도록 수정
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
Labels: ✨ Feature, 🖌️Design

#765 [design/#764] 연장 근로 신청 후 연장 신청 현황 페이지로 이동
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
Labels: 🖌️Design

#767 [fix/#766] vaction 반차 시 쿼터 단위로 신청 가능하게 수정
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: 🐞 BugFix

#769 [refactor/#768] 공지사항 수정 라우터 변경
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🔨 Refactor

#771 [setting#770] cicd 세팅
  Backend/Heroes/Dockerfile
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/controller/EmailController.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailServiceImpl.java
  Backend/Heroes/src/main/resources/application.yml
  Frontend/Dockerfile
  k8s/.gitignore
  k8s/frontend/frontend-deploy.yaml
  k8s/frontend/frontend-service.yaml
  k8s/heroes/heroes-deploy.yaml
  k8s/heroes/heroes-frontend-deploy.yaml
  k8s/heroes/heroes-frontend-service.yaml
  k8s/heroes/heroes-service.yaml
  k8s/heroes/redis-deploy.yaml
  k8s/heroes/redis-service.yaml
  k8s/ingress/ingress-omos.yaml
  k8s/mariadb/mariadb-config.yaml
  k8s/mariadb/mariadb-deployment.yaml
  k8s/mariadb/mariadb-pv.yaml
  k8s/mariadb/mariadb-pvc.yaml
  k8s/mariadb/mariadb-secret.yaml
  k8s/mariadb/mariadb-service.yaml
  k8s/role/jenkins-role-binding.yaml
  k8s/service/auth-deploy.yaml
  k8s/service/auth-hpa.yaml
  k8s/service/auth-service.yaml
  k8s/service/calendar-deploy.yaml
  k8s/service/calendar-hpa.yaml
  k8s/service/notice-deploy.yaml
  k8s/service/notice-hpa.yaml
  k8s/service/notice-service.yaml
  k8s/service/notification-deploy.yaml
  k8s/service/notification-hpa.yaml
  k8s/service/notification-service.yaml
  k8s/service/student-deploy.yaml
  k8s/service/student-hpa.yaml
  k8s/service/student-service.yaml
Labels: ⚙ Setting

#775 [refactor/#774] 날짜 형식 2024.11. 4 -> 2024-11-04 로 변경
  Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
Labels: 🔨 Refactor

#779 [design/#778] salaryStatement design update
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#781 [feat/#780] 승인 안된 대기중인 휴가일수의 합이 잔여 휴가일수 넘어갈 경우 제출 안되게 수정
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: ✨ Feature, 🖌️Design

#783 [refactor/#782] 회원가입시 부서에 속한 팀만 보이게 수정
  Frontend/src/views/pages/auth/SignUpPage.vue
Labels: 🔨 Refactor

#789 [refactor/#788] 급여 명세서 성과급 출력 조건 변경
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🔨 Refactor

#791 [refactor/#790] 프론트 디자인 수정
  Frontend/src/layout/AppMenu.vue
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
  Frontend/src/views/pages/HQattendance/overtime/approve-overtime.vue
  Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
  Frontend/src/views/pages/education/education-management/ApproveEducation.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
  Frontend/src/views/pages/evaluation/EvaluationListPage.vue
Labels: 🔨 Refactor, 🖌️Design

#792 [cicd] 젠킨스 파일 추가
  Frontend/Jenkinsfile
  Jenkinsfile
Labels: ⚙ Setting

#794 [refactor/#793] ToString 제거 및 JobId -> JobRoleId로 변경
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationsReqDTO.java
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🔨 Refactor

#796 [refactor/#795] front 기능 수정
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🔨 Refactor

#798 [feat/#797] 개인 일정 삭제 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
Labels: ✨ Feature, 🖌️Design

#800 [feat/#799] 캘린더 개인 일정 삭제 및 일정 변경 수정 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
  Frontend/src/views/pages/admin/EducationUpdatePage.vue
  Frontend/src/views/pages/admin/EducationWritePage.vue
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/admin/NoticeUpdatePage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/admin/service/adminNoticeService.js
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/service/fetchReissue.js
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/main/service/noticeService.js
  Frontend/src/views/pages/main/service/notificationService.js
  Frontend/src/views/pages/retirement/service/retirementService.js
  Frontend/src/views/pages/salary/workService.js
Labels: ✨ Feature, 🔨 Refactor

#804 [fix/#803] 안쓰는 매서드 제거
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
Labels: 🐞 BugFix
