Repository beyond-sw-camp/be08-fin-HQ-Heroes, pull requests merged in 2024-10, with the labels that each got.

#151 [refactor#150] feedback -> evaluation로 이름 수정 및 엔티티 수정
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationTemplate.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/controller/FeedbackController.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/dto/FeedbackDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/enums/FeedbackStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/repository/FeedbackReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackService.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackServiceImpl.java
Labels: 🔨 Refactor

#153 [feat#152] 평가 기능 클래스 추가
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationCriteria.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationTemplate.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationCriteriaRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/evaluation/EvaluationPage.vue
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
Labels: ✨ Feature

#155 [design/#154] admin Employee Info Update
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
Labels: 🖌️Design

#157 [design/#156] 교육 및 자격증 수정
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
Labels: 🖌️Design

#159 [design/#158] notice list sort 및 admin employee 상세 정보 input readonly 제거
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
Labels: 🖌️Design

#161 [design/#160] 휴가 신청 기능 추가
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: 🖌️Design

#163 [feat/#162] 퇴직금 조회 기능 구현 및 경로 이름 수정
  Backend/Heroes/src/main/java/com/hq/heroes/retire/controller/RetireController.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/dto/RetireDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/dto/RetireRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/dto/RetireResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/repository/RetireRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/service/RetireService.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/service/RetireServiceImpl.java
  Frontend/src/router/index.js
  Frontend/src/views/pages/retire/retirement-funds.vue
  Frontend/src/views/pages/retirement/retirement-funds.vue
  Frontend/src/views/pages/retirement/service/retirementService.js
Labels: ✨ Feature

#165 [feat#164] 평가 기준 및 평가 기록 조회, 등록, 수정, 삭제 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
Labels: ✨ Feature

#169 [feat#168] 회원가입 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
Labels: ✨ Feature

#171 [feat#170] employeeId, password로 로그인, 로그아웃 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/OAuth2Controller.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/CustomEmployeeDetails.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/LoginDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/CustomOAuth2Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/GoogleResponse.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/NaverResponse.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/OAuth2EmployeeDto.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/OAuth2Response.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomOAuth2SuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/RefreshRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomOAuth2UserService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomUserDetailsService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/OAuth2JwtHeaderService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
Labels: ✨ Feature

#173 [feat#172] 교육 엔티티 수정 및 추가
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/CertificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/educationCategory/entity/EducationCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/educationCurriculum/entity/EducationCurriculum.java
  Backend/Heroes/src/main/java/com/hq/heroes/employeeCertification/entity/EmployeeCertification.java
Labels: ✨ Feature

#175 [feat#174] 백, 프론트 회원 가입 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/router/index.js
  Frontend/src/service/authService.js
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/OAuth2Redirect.vue
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/auth/service/authService.js
Labels: ✨ Feature

#177 [feat/#176] 교육 & 자격증 엔티티 수정 및 추가
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
Labels: ✨ Feature

#179 [feat#178] 로그인 및 로그아웃 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/stores/authStore.js
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/service/authService.js
Labels: ✨ Feature

#181 [feat/#180] 급여 기능 구현 및 PK 이름 수정
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
Labels: ✨ Feature

#185 [design/#184] NoticeWritePage 디자인 수정
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🖌️Design

#187 [design#186] 알림 발송 페이지 수정
  Frontend/src/service/NodeService.js
  Frontend/src/views/pages/admin/SendNotificationPage.vue
  Frontend/src/views/pages/auth/service/authService.js
Labels: 🖌️Design

#193 [feat#192] 로그인 기능 구현 및 후처리
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/ReissueController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/main.js
  Frontend/src/stores/authStore.js
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/auth/service/fetchReissue.js
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
Labels: ✨ Feature

#195 [design/#194] 교육 및 자격증 페이지 수정
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: 🖌️Design

#197 [design/#196] 휴가 현황 삭제 및 토글 단순화
  Frontend/src/layout/AppMenu.vue
  Frontend/src/views/pages/HQattendance/attendanceStatus/leave-status.vue
Labels: 🖌️Design

#199 [refactor#198] department_id -> dept_id
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
Labels: 🔨 Refactor

#201 [refactor/#200] 경로 수정
  Frontend/src/router/index.js
Labels: 🔨 Refactor

#204 [feat#203] employee feat and refactor
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: ✨ Feature, 🔨 Refactor

#206 [feat/#205] Deduct 엔티티 생성
  Backend/Heroes/src/main/java/com/hq/heroes/deduct/entity/Deduct.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/controller/RetireController.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/dto/RetireRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/dto/RetireResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/repository/RetireRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/service/RetireService.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/service/RetireServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Frontend/package-lock.json
Labels: ✨ Feature

#208 [feat/#207]교육 및 자격증 entity 수정
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
Labels: ✨ Feature

#210 [feat/#209] attendance 엔티티 수정
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
Labels: ✨ Feature

#212 [feat/#211] salary Date -> LocalDateTime 변경
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
Labels: ✨ Feature

#217 [feat/#216] attendanceServiceImpl 변경
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
Labels: ✨ Feature

#219 [feat#218] 파일 업로드 기능 구현중
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/UploadProperties.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/resources/application.yml
Labels: ✨ Feature

#221 [refactor/#220] noticeCategory column 이름 오타 수정
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/NoticeCategory.java
Labels: 🔨 Refactor

#223 [feat/#222] 업로드 된 파일 가져오기 구현
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
Labels: ✨ Feature

#225 [refactor/#224] employeeList 수정
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
Labels: 🔨 Refactor

#228 [refactor#227] JPA ToString 문제 해결
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/LoginDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/DepartmentDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/JobDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/PositionDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/TeamDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationCriteria.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/NoticeCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/NotificationCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Deduct.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
  Frontend/src/layout/AttendanceBox.vue
Labels: 🔨 Refactor

#232 [feat#231] 평가 관련 CRUD 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationFormController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationForm.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationFormService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationFormServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
Labels: ✨ Feature

#234 [design/#233] 관리자 교육 및 자격증 수정 그리고 사원 교육 및 자격증 수정
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: 🖌️Design

#236 [design/#235] 휴가 신청 페이지 수정
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: 🖌️Design

#238 [feat/#237] 휴가 신청 기능 추가
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
Labels: ✨ Feature

#240 [refactor/#239] 파일 업로드 로직 변경
  Backend/Heroes/build.gradle
  Backend/Heroes/files/11313wedwe_profile.png
  Backend/Heroes/files/1eeeee_profile.png
  Backend/Heroes/files/2024105195_profile.png
  Backend/Heroes/files/2144123455_profile.png
  Backend/Heroes/files/22_profile.png
  Backend/Heroes/files/341256323241_profile.png
  Backend/Heroes/files/555555555555_profile.png
  Backend/Heroes/files/6666666_profile.png
  Backend/Heroes/files/777777_profile.png
  Backend/Heroes/files/null_profile.png
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/UploadProperties.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
  Backend/Heroes/src/main/resources/application.yml
  Backend/Heroes/src/main/resources/static/files/11313wedwe_profile.png
  Backend/Heroes/src/main/resources/static/files/1eeeee_profile.png
  Backend/Heroes/src/main/resources/static/files/2024105195_profile.png
  Backend/Heroes/src/main/resources/static/files/2144123455_profile.png
  Backend/Heroes/src/main/resources/static/files/22_profile.png
  Backend/Heroes/src/main/resources/static/files/341256323241_profile.png
  Backend/Heroes/src/main/resources/static/files/555555555555_profile.png
  Backend/Heroes/src/main/resources/static/files/6666666_profile.png
  Backend/Heroes/src/main/resources/static/files/777777_profile.png
  Backend/Heroes/src/main/resources/static/files/null_profile.png
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🔨 Refactor

#242 [feat/#241] notice 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeCategoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeCategoryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/service/adminNoticeCategoryService.js
  Frontend/src/views/pages/admin/service/adminNoticeService.js
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/main/MainPage.vue
Labels: ✨ Feature

#244 [feat#243] 파이어베이스 이미지 업로드 구현
  Backend/Heroes/.gitignore
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/FirebaseConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/service/FirebaseStorageService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeCategoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeCategoryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/service/adminNoticeCategoryService.js
  Frontend/src/views/pages/admin/service/adminNoticeService.js
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/main/MainPage.vue
Labels: ✨ Feature

#246 [refactor#245] 파이어베이스 작업중 누락 파일 추가
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeCategoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeCategoryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/service/adminNoticeCategoryService.js
  Frontend/src/views/pages/admin/service/adminNoticeService.js
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🔨 Refactor

#248 [design#247] 평가 및 회원가입 UI 수정
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
  Frontend/src/views/pages/evaluation/EvaluationListPage.vue
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
Labels: ✨ Feature, 🖌️Design

#250 [feat#249] 로컬 스토리지에 access JWT토큰을 통해 api요청 구현, 재갱신 구현 중
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
  Frontend/package-lock.json
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/stores/authStore.js
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/auth/service/fetchReissue.js
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
  Frontend/src/views/pages/evaluation/EvaluationListPage.vue
Labels: ✨ Feature

#252 [refactor/#251] 공지사항 삭제, 추가 구현
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeCategoryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeCategoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/service/adminNoticeService.js
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🔨 Refactor

#254 [feat#253] 재 갱신 기능 구현
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/auth/service/fetchReissue.js
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
Labels: ✨ Feature, 🖌️Design

#258 [feat/#257] 휴가 승인페이지(사원) 추가
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: ✨ Feature, 🖌️Design

#262 [feat#261] 알림 api 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/NotificationCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
Labels: ✨ Feature

#264 [feat/#263] profile Update
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: ✨ Feature

#266 [design#265] 부서별 평가 기준 화면 구현
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationCriteriaController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationCriteriaRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
Labels: ✨ Feature, 🖌️Design

#268 [design/#267] 관리자 교육 페이지 수정 & 공지사항 수정 페이지에 카테고리 추가
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🖌️Design

#270 [feat#269] 평가 등록 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
  Frontend/src/views/pages/evaluation/EvaluationListPage.vue
Labels: ✨ Feature

#272 [feat/#271] 자격증 엔티티 수정, 교육 & 자격증 코드 수정
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
Labels: ✨ Feature

#274 [fix#273] fetchPost 상태코드 수정 200 -> 201 무한 reissue발생 버그 해결
  Frontend/src/views/pages/auth/service/AuthApiService.js
Labels: 🐞 BugFix

#276 [feat#275] jwt filter에서 역할, 사용자 ID 확인 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/CustomEmployeeDetails.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/evaluation/EvaluationDetailPage.vue
Labels: ✨ Feature

#278 [feat/#277] 휴가 승인(관리자, 팀장) 페이지 추가
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: ✨ Feature

#280 [feat/#279] Update Modal SelectBox 구현중 ..
  Backend/Heroes/files/11313wedwe_profile.png
  Backend/Heroes/files/1eeeee_profile.png
  Backend/Heroes/files/2024105195_profile.png
  Backend/Heroes/files/2144123455_profile.png
  Backend/Heroes/files/22_profile.png
  Backend/Heroes/files/341256323241_profile.png
  Backend/Heroes/files/555555555555_profile.png
  Backend/Heroes/files/6666666_profile.png
  Backend/Heroes/files/777777_profile.png
  Backend/Heroes/files/null_profile.png
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/AdminEmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/PositionRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Backend/Heroes/src/main/resources/static/files/11313wedwe_profile.png
  Backend/Heroes/src/main/resources/static/files/1eeeee_profile.png
  Backend/Heroes/src/main/resources/static/files/2024105195_profile.png
  Backend/Heroes/src/main/resources/static/files/2144123455_profile.png
  Backend/Heroes/src/main/resources/static/files/22_profile.png
  Backend/Heroes/src/main/resources/static/files/341256323241_profile.png
  Backend/Heroes/src/main/resources/static/files/555555555555_profile.png
  Backend/Heroes/src/main/resources/static/files/6666666_profile.png
  Backend/Heroes/src/main/resources/static/files/777777_profile.png
  Backend/Heroes/src/main/resources/static/files/null_profile.png
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: ✨ Feature

#282 [feat/#281] axios에서 fetchGet으로 변경
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: ✨ Feature

#284 [Feat&design/#283] 교육 및 자격증 수정
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/Certification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/EmployeeCertificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/package-lock.json
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageCertificationDetailPage.vue
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
Labels: ✨ Feature, 🖌️Design

#286 [feat#285] 로그인한 팀원의 평가 결과 조회 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/repository/EvaluationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
Labels: ✨ Feature, 🖌️Design

#288 [design#287] 알림 발송 사원 목록 트리 부서 > 팀 > 사원순으로 구현 및 프로필 사진 표시
  Frontend/src/layout/AppLayout.vue
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: ✨ Feature, 🖌️Design

#290 [refactor#289] refresh 토큰 데이터를 Redis를 사용해서 관리하도록 리팩토링
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomLogoutFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/RedisConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/resources/application.yml
Labels: 🔨 Refactor

#292 [feat#291] 평가 기준 관리 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationCriteriaResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/EvaluationCriteria.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationCriteriaServiceImpl.java
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageEvaluationCriteriaPage.vue
Labels: ✨ Feature, 🖌️Design

#294 [feat/#293] 급여 내역 조회 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/DeductController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/DeductDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/DeductRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/DeductService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/DeductServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
  Frontend/src/views/pages/salary/deductService.js
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
Labels: ✨ Feature

#296 [feat#295] 알림 카테고리 파일 추가 및 알림 발송 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationCategoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationCategoryReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationCategoryResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationCategoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationCategoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: ✨ Feature, 🖌️Design

#298 [feat#297] 받은 알림 조회 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/main/service/notificationService.js
Labels: ✨ Feature, 🖌️Design

#300 [feat/#299] : 출퇴근 버튼 사용하여서 근태 관리
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/layout/AttendanceBox.vue
Labels: ✨ Feature

#302 [Feat&design/#301] 교육 및 자격증 수정 및 추가
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/CertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/EmployeeCertificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature, 🖌️Design

#304 [feat/#303] 월 근태 현황 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
Labels: ✨ Feature, 🖌️Design

#306 [refactor#305] System.out -> log.debug로 리팩토링, 필요없는 주석 삭제
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTUtil.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/resources/application.yml
Labels: 🔨 Refactor

#308 [design/#307] 휴가 승인 거절 추가
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: 🖌️Design

#310 [refactor#309] 프론트엔드 안쓰는 파일 및 클래스 정리
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTUtil.java
  Frontend/public/demo/data/countries.json
  Frontend/public/demo/data/customers-large.json
  Frontend/public/demo/data/customers-medium.json
  Frontend/public/demo/data/events.json
  Frontend/public/demo/data/icons.json
  Frontend/public/demo/data/photos.json
  Frontend/public/demo/data/products-orders-small.json
  Frontend/public/demo/data/products-small.json
  Frontend/public/demo/data/products.json
  Frontend/public/demo/data/treenodes.json
  Frontend/public/demo/data/treetablenodes.json
  Frontend/public/demo/images/access/asset-access.svg
  Frontend/public/demo/images/error/asset-error.svg
  Frontend/public/demo/images/flag/flag_placeholder.png
  Frontend/public/demo/images/landing/enterprise.svg
  Frontend/public/demo/images/landing/free.svg
  Frontend/public/demo/images/landing/mockup-desktop.svg
  Frontend/public/demo/images/landing/mockup.svg
  Frontend/public/demo/images/landing/new-badge.svg
  Frontend/public/demo/images/landing/peak-logo.svg
  Frontend/public/demo/images/landing/screen-1.png
  Frontend/public/demo/images/landing/startup.svg
  Frontend/public/demo/images/logo-white.svg
  Frontend/public/demo/images/logo.svg
  Frontend/src/service/CountryService.js
  Frontend/src/service/CustomerService.js
  Frontend/src/service/NodeService.js
  Frontend/src/service/PhotoService.js
  Frontend/src/service/ProductService.js
  Frontend/src/stores/attendanceStore.js
  Frontend/src/views/Dashboard.vue
  Frontend/src/views/pages/Crud.vue
  Frontend/src/views/pages/Documentation.vue
  Frontend/src/views/pages/Empty.vue
  Frontend/src/views/pages/NotFound.vue
  Frontend/src/views/uikit/ButtonDoc.vue
  Frontend/src/views/uikit/ChartDoc.vue
  Frontend/src/views/uikit/FileDoc.vue
  Frontend/src/views/uikit/FormLayout.vue
  Frontend/src/views/uikit/InputDoc.vue
  Frontend/src/views/uikit/ListDoc.vue
  Frontend/src/views/uikit/MediaDoc.vue
  Frontend/src/views/uikit/MenuDoc.vue
  Frontend/src/views/uikit/MessagesDoc.vue
  Frontend/src/views/uikit/MiscDoc.vue
  Frontend/src/views/uikit/OverlayDoc.vue
  Frontend/src/views/uikit/PanelsDoc.vue
  Frontend/src/views/uikit/TableDoc.vue
  Frontend/src/views/uikit/TimelineDoc.vue
  Frontend/src/views/uikit/TreeDoc.vue
Labels: 🔨 Refactor

#312 [design#311] 알림 작성 페이지 디자인 수정
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: 🖌️Design

#314 [feat/#313] 캘린더에 내 일정 추가 기능
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
Labels: ✨ Feature, 🖌️Design

#316 [feat/#315] 캘린더에서 생성하는 이벤트를 저장하기 위한 엔티티
  Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/entity/Event.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/repository/EventRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
Labels: ✨ Feature

#318 [feat/#317] admin update employee
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/AdminEmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/auth/service/authService.js
Labels: ✨ Feature

#320 [refactor/#319] 안쓰는 Import 제거
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
Labels: 🔨 Refactor

#322 [refactor/#321] 안쓰는 import 제거
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/DeductController.java
Labels: 🔨 Refactor

#324 [refactor#323] 백, 프론트 코드 리팩토링
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/LoginDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/controller/EvaluationFormController.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationFormResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Frontend/src/views/pages/auth/Access.vue
  Frontend/src/views/pages/auth/Error.vue
Labels: 🔨 Refactor

#326 [fix/#325] salary 지급 상태 오류 수정
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🐞 BugFix

#328 [refactor/#327] employeeRefactor
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/AdminEmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/PositionRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Frontend/src/views/pages/admin/UpdateEmpInfoModal.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/auth/service/authService.js
Labels: 🔨 Refactor

#330 [refator/#329] import문 수정
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
Labels: 🔨 Refactor

#332 [design/#331] profile readonly 속성 디자인
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#334 [refactor#333] 설명 주석 추가
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/RedisConfig.java
  Frontend/src/views/pages/auth/service/authService.js
Labels: 🔨 Refactor

#338 [feat#337] 회원가입 유효성 검사 추가
  Frontend/src/views/pages/auth/SignUpPage.vue
Labels: ✨ Feature

#340 [design/#339] 월 근태, 휴가 승인 DataTable 수정
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: 🖌️Design

#344 [design/#343] AttendanceBox에 프로필 이미지 추가, 퇴근 색상 변경
  Frontend/src/layout/AttendanceBox.vue
Labels: 🖌️Design

#346 [Feat&design/#345] 교육 수정
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/enums/CourseStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature, 🖌️Design

#348 [Feat&design/#347] 자격증 수정
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
  Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
Labels: ✨ Feature, 🖌️Design

#350 [feat/#349] salary 엔터티 생성 및 조회 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/DeductDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryHistoryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/SalaryHistory.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/DeductRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
Labels: ✨ Feature

#356 [feat/#355] fetchPost 수정 및 출퇴근 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/views/pages/auth/service/AuthApiService.js
Labels: ✨ Feature, 🖌️Design

#358 [design/#357] 총 근무시간 시간, 분, 초 단위로 변경
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🖌️Design

#360 [feat/#359] 공제액 조회 구현
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
  Frontend/src/views/pages/salary/deductService.js
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
Labels: ✨ Feature

#362 [feat/#361] create notice
  Backend/Heroes/src/main/java/com/hq/heroes/common/controller/ImageUploadController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/EducationWritePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: ✨ Feature

#363 [feat#353] 관리자 로그인 시 인증번호 메일로 발송 및 2차 인증 구현
  Backend/Heroes/build.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/RefreshRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/controller/EmailController.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/dto/AuthCodeReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailMessage.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailReqDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/dto/EmailResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/entity/AuthCode.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailService.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Backend/Heroes/src/main/resources/application.yml
  Backend/Heroes/src/main/resources/templates/mails/authCode.html
  Backend/Heroes/src/main/resources/templates/mails/changePassword.html
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/auth/service/fetchReissue.js
Labels: ✨ Feature

#366 [feat#354] 비밀번호 재발급 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/common/controller/EmailController.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/dto/ResetPWDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/service/EmailServiceImpl.java
  Backend/Heroes/src/main/resources/templates/mails/resetPassword.html
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/ResetPWPage.vue
Labels: ✨ Feature, 🖌️Design

#368 [feat/#367] 안읽은 알림개수 AttendanceBox에 표시
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/layout/AttendanceBox.vue
Labels: ✨ Feature, 🖌️Design

#370 [design/#369] 급여 상태(지급, 미지급) 색 변경
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#372 [Feat&design/#371]certification
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/CertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/controller/EmployeeCertificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/dto/EmployeeCertificationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/entity/EmployeeCertification.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/repository/CertificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/CertificationServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/certification/service/EmployeeCertificationServiceImpl.java
  Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature, 🖌️Design

#374 [design#373] 발송자 표시 및 사원 트리 검색 필터 추가
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: ✨ Feature, 🖌️Design

#376 [feat/#375] 메인 페이지에 출퇴근 시간 출력
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/main/service/attendanceService.js
Labels: ✨ Feature, 🖌️Design

#378 [feat/#377] 공제액 계산 함수 생성 및 실지급액 계산
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: ✨ Feature

#380 [design/#379] Appmenu, 공지사항 페이지 디자인 수정
  Frontend/src/layout/AppMenu.vue
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#382 [feat/#381] 캘린더 이벤트 추가 기능
  Backend/Heroes/src/main/java/com/hq/heroes/event/controller/EventController.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/dto/EventDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/entity/Event.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventService.java
  Backend/Heroes/src/main/java/com/hq/heroes/event/service/EventServiceImpl.java
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
Labels: ✨ Feature, 🖌️Design

#384 [feat#383] 알림 열람 상태 변경 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/views/pages/auth/service/AuthApiService.js
  Frontend/src/views/pages/main/MainPage.vue
Labels: ✨ Feature

#386 [feat/#385] 자신의 휴가 내역만 보이도록 설정
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: ✨ Feature, 🖌️Design

#388 [feat/#387] 공지사항 조회, 삭제 기능
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Frontend/package-lock.json
  Frontend/src/main.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
Labels: ✨ Feature, 🖌️Design

#392 [design/#390] 휴가 승인 페이지와 휴가 상태 확인 페이지 분리
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
Labels: 🖌️Design

#394 [Feat&design/#393] 교육 페이지 수정
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature, 🖌️Design

#396 [refactor/#395] education 및 course Entity 리팩토링
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationCurriculumDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/EducationCurriculum.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationCurriculumRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🔨 Refactor

#398 [refactor/#397] educationId 타입 long -> Long
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
Labels: 🔨 Refactor

#400 [design/#399] 공지사항 hover 적용
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🖌️Design

#402 [feat/#401] 휴가 승인 페이지 자신에게 온 신청만 보이게 수정
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: ✨ Feature, 🖌️Design

#404 [feat/#403] Write Education
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/views/pages/admin/EducationWritePage.vue
Labels: ✨ Feature

#406 [feat/#405] 특정 사원의 월별 총 근무 시간 조회
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
  Frontend/src/views/pages/salary/workService.js
Labels: ✨ Feature

#410 [design/#409] 교육 신청하기 및 수강 정원 추가하기
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: 🖌️Design

#412 [design#411] 로그인 페이지 디자인 수정
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/main.js
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/LoginPage.vue
Labels: 🖌️Design

#414 [design#413] 상단 바에서 알림 Drawer 열기 구현
  Frontend/src/layout/AppTopbar.vue
Labels: 🖌️Design

#416 [feat#415] 보낸알림, 받은알림 필터 구현 및 알림 리스트 디자인 수정
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/main/service/notificationService.js
Labels: ✨ Feature, 🖌️Design

#418 [feat/#417] 퇴근하기와 동시에 로그아웃 되게 설정
  Frontend/src/layout/AttendanceBox.vue
Labels: ✨ Feature

#420 [feat/#419] 연장 근로 관련 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/dto/OvertimeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/entity/Overtime.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/entity/enums/OvertimeStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/repository/OvertimeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
  Frontend/src/views/pages/HQattendance/overtime/approve-overtime.vue
  Frontend/src/views/pages/HQattendance/overtime/status-overtime.vue
Labels: ✨ Feature, 🖌️Design

#422 [design#421] 알림 관리 Drawer 디자인 수정
  Frontend/src/layout/AppTopbar.vue
Labels: 🖌️Design

#424 [refactor/#423] 공지사항 수정 - 취소 - 수정 시 에디터 내용 보이기 작업중..
  Frontend/package-lock.json
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
Labels: 🔨 Refactor

#426 [desgin#425] 알림 관리, 메인 알림 영역 정렬 수정 및 디자인 수정, 삭제 버튼 추가
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/main/MainPage.vue
Labels: ✨ Feature, 🖌️Design

#428 [feat#427] 알림 삭제 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/notification/SendNotificationPage.vue
Labels: ✨ Feature, 🖌️Design

#430 [feat/#429] add courseList
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Backend/Heroes/src/main/resources/application.yml
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature

#432 [design/#431] 관리자 모드에서 교육 및 공지사항 수정
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🖌️Design

#434 [feat/#433] 교육 등록 시 이미지 저장로직 추가
  Frontend/src/views/pages/admin/EducationWritePage.vue
Labels: ✨ Feature

#436 [feat/#435] 급여 조회 기능 수정 (fetchGet으로 변경)
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryService.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
  Frontend/package.json
  Frontend/src/views/pages/salary/deductService.js
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
Labels: ✨ Feature

#438 [feat/#437] 다른 팀원 휴가 신청 가능
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: ✨ Feature, 🖌️Design

#440 [Feat&design/#439] education
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/views/pages/admin/ManageEducationDetailPage.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
Labels: ✨ Feature, 🖌️Design

#442 [feat/#441] 휴가 신청자, 결재자, 대리인 구분 구현
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: ✨ Feature

#443 [feat] 신청자, 대리인, 결재자 requestBody에 추가
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: ✨ Feature

#446 [feat/#444] 퇴직금 조회 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/EmployeeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/controller/SalaryHistoryController.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/RetireDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryHistoryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
  Frontend/src/views/pages/retirement/retirement-funds.vue
  Frontend/src/views/pages/retirement/service/retirementService.js
Labels: ✨ Feature

#447 [feat/ #445] 공지사항 작성 시 이미지 크기 고정 및 페이지 이동
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Frontend/src/views/pages/admin/EducationWritePage.vue
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
  Frontend/src/views/pages/admin/service/adminNoticeService.js
Labels: ✨ Feature

#449 [feat/#448] 휴가에서 applicant, employee, approver 구분
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
  Frontend/src/views/pages/HQattendance/vacation/status-vacation.vue
Labels: ✨ Feature

#451 [design/#450] 모달창 클릭 시 블러 처리
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#453 [Feat&design/#452] education
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/package-lock.json
  Frontend/src/views/pages/education/certificate-management/CertificationDetail.vue
  Frontend/src/views/pages/education/certificate-management/EmployeeCertificationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: ✨ Feature, 🖌️Design

#455 [feat/#454] 공지사항 취소
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
Labels: ✨ Feature

#457 [feat/#456] 보류중(ON_HOLD) 추가 및 18:10까지 퇴근기록 없다면 보류 상태로 변경하는 코드 추가
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/views/pages/main/MainPage.vue
Labels: ✨ Feature, 🖌️Design

#459 [feat/#458] 비밀번호 변경 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/PasswordUpdateDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/service/EmployeeServiceImpl.java
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/views/pages/auth/service/authService.js
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: ✨ Feature, 🖌️Design

#461 [feat/#460] 공지사항 업데이트 진행중..
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/views/pages/admin/NoticeDetailPage.vue
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: ✨ Feature

#463 [design/#462] 자격증 및 교육 검색 부분 수정
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationDetail.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: 🖌️Design

#465 [feat/#464] 연장 근로 시간 체크
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/controller/OvertimeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/repository/OvertimeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/overtime/service/OvertimeServiceImpl.java
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
Labels: ✨ Feature, 🖌️Design

#469 [refactor/#468] notice resize
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🔨 Refactor

#471 [refactor/#470] notice 뒤로가기 router 설정
  Frontend/src/views/pages/admin/NoticeWritePage.vue
Labels: 🔨 Refactor

#473 [design/#472] 공지사항 목록 검색 버튼 위치 변경
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#475 [feat#474] 평가 결과 리스트 항목 수정
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/dto/EvaluationResDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/entity/Evaluation.java
  Backend/Heroes/src/main/java/com/hq/heroes/evaluation/service/EvaluationServiceImpl.java
  Frontend/src/views/pages/evaluation/EvaluationResultPage.vue
Labels: ✨ Feature, 🖌️Design

#477 [Feat&design/#476] 교육 페이지 추가
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/CourseContoller.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/CourseServiceImpl.java
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/education/education-management/ApproveEducation.vue
  Frontend/src/views/pages/education/education-management/EducationDetailModal.vue
Labels: ✨ Feature, 🖌️Design

#479 [feat/#478] 급여 계산 기능 수정(1년마다 매년 5% 증가)
  Backend/Heroes/src/main/java/com/hq/heroes/salary/dto/SalaryDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/repository/SalaryRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryHistoryServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/service/SalaryServiceImpl.java
  Frontend/src/views/pages/salary/salary-statement.vue
  Frontend/src/views/pages/salary/salaryService.js
Labels: ✨ Feature

#481 [refactor/#480] fetch import 추가
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: 🔨 Refactor
