Repository beyond-sw-camp/be08-fin-HQ-Heroes, pull requests merged in 2024-09, with the labels that each got.

#4 [desing/#3] 프로젝트 이름 수정
  Frontend/src/layout/AppTopbar.vue
Labels: 🖌️Design

#6 [setting/#5] kubernetes 파일 세팅
  k8s/frontend/frontend-deploy.yaml
  k8s/frontend/frontend-service.yaml
  k8s/ingress/ingress-omos.yaml
  k8s/mariadb/mariadb-config.yaml
  k8s/mariadb/mariadb-deployment.yaml
  k8s/mariadb/mariadb-pv.yaml
  k8s/mariadb/mariadb-pvc.yaml
  k8s/mariadb/mariadb-secret.yaml
  k8s/mariadb/mariadb-service.yaml
  k8s/role/jenkins-role-binding.yaml
  k8s/service/auth-deploy.yaml
  k8s/service/auth-hpa.yaml
  k8s/service/auth-service.yaml
  k8s/service/calendar-deploy.yaml
  k8s/service/calendar-hpa.yaml
  k8s/service/calendar-service.yaml
  k8s/service/notice-deploy.yaml
  k8s/service/notice-hpa.yaml
  k8s/service/notice-service.yaml
  k8s/service/notification-deploy.yaml
  k8s/service/notification-hpa.yaml
  k8s/service/notification-service.yaml
  k8s/service/student-deploy.yaml
  k8s/service/student-hpa.yaml
  k8s/service/student-service.yaml
Labels: ⚙ Setting

#8 [design/#7] 인사시스템 사이드바 메뉴 수정
  .vscode/launch.json
  Frontend/src/layout/AppMenu.vue
  Frontend/src/layout/AppSidebar.vue
  Frontend/src/layout/AttendanceBox.vue
Labels: 🖌️Design

#10 design : 다크모드 수정, 앱메뉴 정리
  Frontend/src/layout/AppMenu.vue
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/Landing.vue
  Frontend/src/views/pages/calendar/CalendarPage.vue
  Frontend/src/views/pages/feedback/FeedBack.vue
Labels: 🖌️Design

#14 [design/#13] 평가 결과 페이지, 다면 평가 페이지 구현
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/layout/AppMenu.vue
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/main.js
  Frontend/src/router/index.js
  Frontend/src/views/pages/feedback/FeedBack.vue
  Frontend/src/views/pages/feedback/FeedBackResult.vue
Labels: 🖌️Design

#16 [Design/#15]change employee
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
  Frontend/src/views/pages/studentDetail/StudentDetailModal.vue
  Frontend/src/views/pages/studentlist/StudentListPage.vue
Labels: 🖌️Design

#18 [design/#17] 근태, 교육 캘린더 프론트 구현
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/attendance/attendance-calendar/AttendanceCalendar.vue
  Frontend/src/views/pages/attendance/attendance-calendar/utils/data.js
  Frontend/src/views/pages/attendance/attendance-calendar/utils/event-utils.js
  Frontend/src/views/pages/calendar/utils/data.js
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
  Frontend/src/views/pages/education/education-calendar/EducationCalendar.vue
  Frontend/src/views/pages/education/education-calendar/utils/data.js
  Frontend/src/views/pages/education/education-calendar/utils/event-utils.js
Labels: 🖌️Design

#22 [design/#21] router.js HQattendance 경로 수정
  Frontend/src/router/index.js
Labels: 🖌️Design

#25 [design/#23] 사용자 인증 화면 일반 로그인, 관리자 로그인, 회원가입, 비밀번호 재발급 페이지 퍼블리싱
  Frontend/src/components/FloatingConfigurator.vue
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/Login.vue
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/ResetPWPage.vue
  Frontend/src/views/pages/auth/SignUpPage.vue
  Frontend/src/views/pages/feedback/FeedBackPage.vue
  Frontend/src/views/pages/feedback/FeedBackResultPage.vue
Labels: 🖌️Design

#27 [design/#26] topbar 로고 부분 수정
  Frontend/src/layout/AppTopbar.vue
Labels: 🖌️Design

#28 [Design/#24]salary page 퍼블리싱
  Frontend/src/router/index.js
  Frontend/src/views/pages/salary/SalaryDetails.vue
  Frontend/src/views/pages/salary/SalarySummary.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#30 [design/#29] 급여 페이지 퍼블리싱
  Frontend/src/views/pages/salary/SalaryDetails.vue
  Frontend/src/views/pages/salary/SalarySummary.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#32 [design/#31] 휴가 페이지 수정
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/attendanceStatus/leave-status.vue
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
Labels: 🖌️Design

#34 [design/#33] 자격증 관리 페이지
  Frontend/src/router/index.js
  Frontend/src/views/pages/education/certificate-management/CertificationList.vue
Labels: 🖌️Design

#36 [design/#35] 급여 페이지 수정
  Frontend/src/views/pages/salary/SalarySummary.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#38 [design/#37] 관리자 사이드바 메뉴 추가
  Frontend/src/layout/AppMenu.vue
  Frontend/src/layout/AppTopbar.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/auth/AdminLoginPage.vue
  Frontend/src/views/pages/auth/LoginPage.vue
  Frontend/src/views/pages/auth/SignInDialog.vue
  Frontend/src/views/pages/auth/SignUpDialog.vue
Labels: 🖌️Design

#40 [design/#39] 관리자 기능 라우터 작성
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: 🖌️Design

#42 [design/#41] 관리자 알림 발송 페이지 수정
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
  Frontend/src/views/pages/admin/SendNotificationPage.vue
Labels: 🖌️Design

#45 [design/#44] 웹 사이트 제목 및 아이콘 변경
  Frontend/index.html
  Frontend/public/favicon.ico
Labels: 🖌️Design

#46 [design/#43] 관리자 교육 페이지 추가
  Frontend/src/layout/AppMenu.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
Labels: 🖌️Design

#48 [design/#47] 관리자 자격증 페이지 추가
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
Labels: 🖌️Design

#50 [design/#49] 휴가 페이지 수정
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
Labels: 🖌️Design

#52 [design/#51] 메인 페이지 알림부분 메세지로 수정
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🖌️Design

#54 [design/#53] 출퇴근 시간, 휴가 일수, 급여 카드 수정
  Frontend/src/views/pages/main/MainPage.vue
Labels: 🖌️Design

#56 [design/#55] add profile
  Frontend/index.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/router/index.js
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#58 [design/#57] 급여 페이지 수정
  Frontend/src/views/pages/salary/SalaryDetails.vue
  Frontend/src/views/pages/salary/SalarySummary.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#60 [design/#59] 퇴직금 조회 페이지 퍼블리싱
  Frontend/src/router/index.js
  Frontend/src/views/pages/retire/retirement-funds.vue
Labels: 🖌️Design

#62 [design /#61] profile final
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#65 [design/#63] 사원 정보 수정 페이지, 사이드 바 아이콘 추가
  Frontend/src/layout/AppMenu.vue
  Frontend/src/views/pages/admin/UpdateEmpInfoPage.vue
  Frontend/src/views/pages/feedback/FeedBackPage.vue
  Frontend/src/views/pages/feedback/FeedBackResultPage.vue
Labels: 🖌️Design

#66 [design/#64] : 공지사항 페이지 퍼블리싱
  Frontend/src/router/index.js
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#68 [design/#67] 관리자 교육, 자격증 페이지 정렬 적용
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
Labels: 🖌️Design

#70 [setting/#69] Backend 개발 환경 세팅
  .idea/.gitignore
  .idea/be08-fin-HQ-Heroes.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Backend/Heroes/.gitignore
  Backend/Heroes/build.gradle
  Backend/Heroes/gradle/wrapper/gradle-wrapper.properties
  Backend/Heroes/gradlew
  Backend/Heroes/gradlew.bat
  Backend/Heroes/settings.gradle
  Backend/Heroes/src/main/java/com/hq/heroes/HeroesApplication.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/OAuth2Controller.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/controller/SignController.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/CustomEmployeeDetails.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/JoinDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/form/LoginDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/CustomOAuth2Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/GoogleResponse.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/NaverResponse.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/OAuth2EmployeeDto.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/dto/oAuth2/OAuth2Response.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/RefreshToken.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/enums/Role.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/enums/Status.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomFormSuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomLogoutFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/handler/CustomOAuth2SuccessHandler.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTFilter.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/jwt/JWTUtil.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/RefreshRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomOAuth2UserService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomUserDetailsService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/OAuth2JwtHeaderService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/RefreshTokenService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/ReissueService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/util/CookieUtil.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SecurityConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/SwaggerConfig.java
  Backend/Heroes/src/main/java/com/hq/heroes/common/config/WebConfig.java
  Backend/Heroes/src/main/resources/application.yml
Labels: ⚙ Setting

#72 [design /#71] employeeList 칭찬기능 삭제 및 상태 추가
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
Labels: 🖌️Design

#74 [design/#73] 휴가 페이지 수정, 라우터 및 사이바 수정
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/attendanceStatus/leave-status.vue
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-non-operation-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
Labels: 🖌️Design

#76 [design/#75] 급여 페이지 수정
  Frontend/package-lock.json
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/salary/SalaryDetails.vue
  Frontend/src/views/pages/salary/SalarySummary.vue
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#78 [feat/#77] 평가, 메시지(공지, 알림) 초기 구현
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/controller/FeedbackController.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/dto/FeedbackDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/repository/FeedbackReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackService.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/service/FeedbackServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/controller/NotificationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/dto/NotificationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/repository/NotificationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/service/NotificationServiceImpl.java
  Backend/Heroes/src/main/resources/application.yml
Labels: ✨ Feature

#81 [design#80] button color change
  Frontend/src/layout/AttendanceBox.vue
  Frontend/src/views/pages/HQattendance/overtime/apply-overtime.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
  Frontend/src/views/pages/admin/ManageCertificatePage.vue
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/admin/SendNotificationPage.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#85 [design/#84] 교육 신청, 교육 이력 페이지 추가
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/education/education-calendar/EducationCalendar.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
  Frontend/src/views/pages/education/education-management/utils/data.js
  Frontend/src/views/pages/education/education-management/utils/event-utils.js
Labels: 🖌️Design

#87 [design/#86] 교육 신청, 교육 이력 페이지 수정
  Frontend/src/views/pages/education/education-management/EducationApply.vue
  Frontend/src/views/pages/education/education-management/EducationHistory.vue
Labels: 🖌️Design

#91 [feat/#90] attendance 초기 세팅 및 자료형 변경
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendacneRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
Labels: ✨ Feature

#93 [feat/#92] education 초기 세팅
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
Labels: ✨ Feature

#95 [feat/#94] 사원 테이블 정의, 사원 고유 ID 생성 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/enums/Status.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/repository/EmployeeRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomOAuth2UserService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/CustomUserDetailsService.java
  Backend/Heroes/src/main/java/com/hq/heroes/auth/service/JoinService.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/resources/application.yml
Labels: ✨ Feature

#97 [feat/#96] entity 매핑설정
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
Labels: ✨ Feature

#99 [feat/#98] education entity 생성
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
Labels: ✨ Feature

#102 [feat/#100] feedback, notice, notification entity setting
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/enums/FeedbackStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/enums/NotificationStatus.java
Labels: ✨ Feature

#104 [feat/#101] attendance 엔티티 및 enum 추가
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/Attendance.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
Labels: ✨ Feature

#105 [feat#103] entity 매핑 수정
  Backend/Heroes/src/main/java/com/hq/heroes/auth/entity/Employee.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Department.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Job.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Position.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/entity/Team.java
Labels: ✨ Feature

#107 [feat/#106] education & course 엔티티 추가 및 매핑 수정
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/course.java
Labels: ✨ Feature

#109 [design/#108] salaryPage 디자인
  Frontend/src/views/pages/salary/salary-statement.vue
Labels: 🖌️Design

#111 [feat/#110] 엔티티 생성 및 자료형 수정
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/enums/Status.java
Labels: ✨ Feature

#113 [fix/#112] entity 부동 소수점 버그 해결
  Backend/Heroes/.gitignore
  Backend/Heroes/src/main/java/com/hq/heroes/feedback/entity/Feedback.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notification/entity/Notification.java
  Backend/Heroes/src/main/java/com/hq/heroes/retire/entity/Retire.java
  Backend/Heroes/src/main/java/com/hq/heroes/salary/entity/Salary.java
  Backend/Heroes/src/main/resources/application.yml
Labels: 🐞 BugFix

#115 [feat/#114] 공지사항 RestAPI 구현 및 적
  Backend/Heroes/src/main/java/com/hq/heroes/notice/controller/NoticeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/dto/NoticeUpdateRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/Notice.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/entity/enums/NoticeCategory.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/repository/NoticeReposiroty.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeService.java
  Backend/Heroes/src/main/java/com/hq/heroes/notice/service/NoticeServiceImpl.java
  Frontend/src/views/pages/main/MainPage.vue
  Frontend/src/views/pages/main/service/noticeService.js
Labels: ✨ Feature

#120 [design/#119] 공지사항 페이지 디자인 수정
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#122 [refactor/#121] employeeList 부서 및 팀 기반 검색 기능 리팩토링
  Backend/Heroes/src/main/java/com/hq/heroes/employee/controller/EmployeeController.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/dto/DepartmentDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/DepartmentRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/employee/repository/TeamRepository.java
  Frontend/src/views/pages/employeeList/EmployeeListPage.vue
Labels: 🔨 Refactor

#124 [design/#123] 공지사항 페이지 수정
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#128 [Feat/#127] 월 근태 현황 조회 기능
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/controller/AttendanceController.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendacneRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/dto/AttendanceDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/entity/enums/AttendanceStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/repository/AttendanceRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceService.java
  Backend/Heroes/src/main/java/com/hq/heroes/attendance/service/AttendanceServiceImpl.java
  Frontend/src/views/pages/HQattendance/attendanceStatus/monthly-attendance-status.vue
Labels: ✨ Feature, 🖌️Design

#130 [feat/#129] vacation 기본 코드
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationStatus.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/repository/VacationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
Labels: ✨ Feature

#132 [design/#131] 공지사항 페이지 수정
  Frontend/src/views/pages/admin/ManageNoticePage.vue
Labels: 🖌️Design

#135 [feat/#134] 공지사항 백엔드 API 통신 구현 및 필터링
  Backend/.idea/Backend.iml
  Backend/.idea/misc.xml
  Backend/.idea/modules.xml
  Backend/.idea/vcs.xml
  Backend/.idea/workspace.xml
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/views/pages/admin/ManageNoticePage.vue
  Frontend/src/views/pages/admin/service/adminNoticeService.js
Labels: ✨ Feature

#137 [Feat/design/#136] 교육 기능 구현
  Backend/Heroes/src/main/java/com/hq/heroes/education/controller/EducationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/CourseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationRequestDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/dto/EducationResponseDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Course.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/entity/Education.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/CourseRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/repository/EducationRepository.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/education/service/EducationServiceImpl.java
  Frontend/src/views/pages/admin/ManageEducationPage.vue
  Frontend/src/views/pages/education/education-management/EducationApply.vue
Labels: ✨ Feature, 🖌️Design

#139 [feat/#138] 휴가 신청, 휴가 조회 기능 추가
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/controller/VacationController.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/dto/VacationDTO.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/Vacation.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/entity/enums/VacationType.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationService.java
  Backend/Heroes/src/main/java/com/hq/heroes/vacation/service/VacationServiceImpl.java
Labels: ✨ Feature

#141 [design/#140] education apply design update
  Frontend/package-lock.json
  Frontend/src/views/pages/education/education-management/EducationApply.vue
Labels: 🖌️Design

#143 [design/#142] profile 파일 업로드시 미리보기 기능 추가
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#145 [design/#144] employee 모달 창 디자인 수정 및 오타 수정
  Frontend/src/views/pages/employeeDetail/EmployeeDetailModal.vue
  Frontend/src/views/pages/profile/ProfilePage.vue
Labels: 🖌️Design

#147 [design/#146] 휴가 승인 페이지 수정 및 경로 변경
  Frontend/src/layout/AppMenu.vue
  Frontend/src/router/index.js
  Frontend/src/views/pages/HQattendance/vacation/approve-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/approve-vacation.vue
Labels: 🖌️Design

#149 [design/#148] 휴가 신청 페이지 수정
  Frontend/src/views/pages/HQattendance/vacation/apply-annual-leave.vue
  Frontend/src/views/pages/HQattendance/vacation/apply-vacation.vue
Labels: 🖌️Design
